name: Continuous Integration Release
run-name: Build started by ${{ github.actor }}

on:
    pull_request:
        branches:
            - main
            - 'release/**'

permissions:
    contents: write

jobs:
    call-build:
        uses: alxss01-reusable/devops-reusable/.github/workflows/java-build.yaml@main

        with:
            sonar-cloud-enabled: ${{ inputs.sonar-cloud-enabled }}
            owasp-zap-enabled: ${{ inputs.owasp-zap-enabled }}
            snyk-enabled: ${{ inputs.snyk-enabled }}


    call_deploy:
        needs: call-build
        uses: alxss01-reusable/devops-reusable/.github/workflows/java-deploy.yaml@main
        with:
            app-version: ${{ needs.call-build.outputs.app-version }}



